name: print-env
run-name: Print Environment Variables

on:
  push:
    branches:
      - main

jobs:
  print-env-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Cargo
        run: cargo build

      - name: Dockerbuild
        run: docker build -t moshidev/localautomate:2.0.0 -f Dockerfile .
      
      - name: Dockerpush
        run: docker push moshidev/localautomate:2.0.0